export const ActionTypes = {
  WIDRAW_MONEY: "WIDRAW_MONEY",
  DEPOSIT_MONEY: "DEPOSIT_MONEY",

  SET_USERS: "SET_USERS",
  SELECTED_USER: "SELECTED_USER",
  REMOVE_SELECTED_USER: "REMOVE_SELECTED_USER",
}